version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.35
    ports:
      - "5775:5775"    # Zipkin Thrift
      - "6831:6831/udp"  # Jaeger UDP trace transport
      - "6832:6832/udp"  # Another UDP trace transport
      - "5778:5778"    # Admin API
      - "16686:16686"  # Jaeger Web UI (for viewing traces)
      - "14250:14250"  # gRPC
      - "14268:14268"  # HTTP endpoint for trace ingestion
      - "14250:14250"  # gRPC
